function isMobile(){var thres_w=740;if($(window).width()<thres_w)return true;return false;}
$(document).ready(function(){function limit(v,range){if(typeof range==='undefined')range=[0.0,1.0];return Math.min(range[1],Math.max(range[0],v));}
var sizing={win:{height:parseFloat($(window).height()),offset:parseFloat($(window).scrollTop())}};function hydratePinMobile(){$("#pin-animation").append('<img src="assets/card-animations/pin/PIN-Lock-screen-1.png">');}
function hydratePin(){for(i=1;i<6;i++){var opacity=1.0;$("#pin-animation").append('<div id="pin-animation-'+i+'" style="z-index:'+(i+4)+';opacity:'+opacity+';position:absolute;top:0px;">'+'<img src="assets/card-animations/pin/PIN-Lock-screen-'+i+'.png"></div>');}}
function hydrateWipeMobile(){$("#wipe-animation").append('<img src="assets/card-animations/wipe/remote_wipe_snapshot_background_state2_mobile.png">');}
function hydrateWipe(){$("#wipe-animation").append('<div id="wipe-animation-phone-1" style="z-index:4;opacity:1.0;position:absolute;top:0px;">'+'<img src="assets/card-animations/wipe/remote_wipe_snapshot_background_state1.png"></div>');$("#wipe-animation").append('<div id="wipe-animation-phone-2" style="z-index:4;opacity:1.0;position:absolute;top:0px;">'+'<img src="assets/card-animations/wipe/remote_wipe_snapshot_background_state2.png"></div>');$("#wipe-animation").append('<div id="wipe-animation-card-1" style="z-index:5;opacity:1.0;position:absolute;top:0px;">'+'<img src="assets/card-animations/wipe/card_screen_citibank_off.png"></div>');$("#wipe-animation").append('<div id="wipe-animation-card-2" style="z-index:5;opacity:1.0;position:absolute;top:0px;">'+'<img src="assets/card-animations/wipe/card_screen_card_reported_lost_on.png"></div>');}
function t(e){if(typeof e==='undefined')e=nutrifio.img.id;return 1.0- limit(parseFloat($(e).offset().top+$(e).outerHeight()/2-sizing.win.offset)/sizing.win.height);}
function remap_to_bounds(v,bounds){if(typeof bounds.begin!=='undefined'&&typeof bounds.end!=='undefined')return limit(parseFloat(v-bounds.begin)/parseFloat(bounds.end-bounds.begin));else return limit(parseFloat(v-bounds[0])/parseFloat(bounds[1]-bounds[0]));}
function d(m){$('#everything-debug').html(m);}
if($('body.wallet').length==0){}
else if(isMobile()){hydratePinMobile();hydrateFacialAnimationMobile();hydrateProximityAnimationMobile();hydrateWipeMobile();}
else{hydratePin();hydrateFacialAnimation();hydrateWipe();hydrateProximityAnimation();positionnutrifio();processPinAnimation();processWipeAnimation();processFacialAnimation();processProximityAnimation();$(window).resize(function(){positionnutrifio();processPinAnimation();processWipeAnimation();processFacialAnimation();processProximityAnimation();});$(window).scroll(function(){sizing.win.offset=parseFloat($(window).scrollTop());processPinAnimation();processWipeAnimation();processFacialAnimation();processProximityAnimation();});}
function hydrateFacialAnimationMobile(){$('#facial-animation').append('<img id="facial-animation-phone" src="assets/card-animatins/facial/phone_mobile.png">');}
function hydrateFacialAnimation(){$('#facial-animation').append('<div id="facial-animation-phone" style="position:absolute;z-index:5; top:0px;left:0px;width:400px;height:460px;"><img src="assets/card-animations/facial/phone.png"></div>');$('#facial-animation').append('<video id="facial-animation-video" width="328" height="270" style="position:absolute; height: auto; width: 328px; left: 0px; top: 0;z-index:6;-moz-user-select:none;"><source data-format="mp4" type="video/mp4" src="assets/card-animations/facial/face.mp4"></source><source data-format="ogv" type="video/ogg" src="assets/card-animations/facial/face.ogv"></source></video>');}
function hydrateProximityAnimationMobile(){$('#proximity-animation-width-reference').html('<img src="assets/card-animations/proximity/phone.png">');}
function hydrateProximityAnimation(){$('#app-proximity-alerts').prepend(['<div id="proximity-animation" style="position:absolute;left:0px;bottom:0px;overflow:hidden;z-index:4;">','<div id="proximity-iphone" style="bottom:0px;left:0px;position:absolute;z-index:8;">','<img src="assets/card-animations/proximity/phone.png">','</div>','<div id="proximity-card" style="top:0px;left:0px;position:absolute;z-index:7;">','<img src="assets/card-animations/proximity/card.png">','</div>','</div>'].join('\n'));}
function processProximityAnimation(){var pos_iphone=remap_to_bounds(t("#app-proximity-alerts"),[0.25,0.5]);var pos_card=remap_to_bounds(t("#app-proximity-alerts"),[0.2,0.4]);var frame_offset=($('#app-proximity-alerts').outerHeight()- $('#proximity-animation').outerHeight())/2.0;$('#proximity-iphone').css('bottom',(-1.0*(1.0-pos_iphone)*$('#proximity-iphone').outerHeight())+'px');var card_ratio=400.0/458.0;var card_width=(0.15+0.85*(1.0-pos_card))*$('#proximity-animation').outerWidth();var card_height=card_width*card_ratio;$('#proximity-card').css('width',card_width+'px');$('#proximity-card').css('height',card_height+'px');$('#proximity-card').css('left',($('#proximity-animation').outerWidth()-card_width)/2.0+'px');$('#proximity-card').css('top',($('#proximity-animation').outerHeight()-card_height)/2.0+'px');}
var facial_run=false;function processFacialAnimation(){if(!facial_run){var facial_pos=t("#facial-animation");if(facial_pos>0.3&&facial_pos<0.85){document.getElementById("facial-animation-video").play();facial_run=true;}}}
function processWipeAnimation(){var wipe_pos=t("#wipe-animation");var opacity_phone_1=(wipe_pos<0.35)?1.0:0.0;var opacity_phone_2=(opacity_phone_1>0.0)?0.0:1.0;var opacity_card_1=(wipe_pos<0.5)?1.0:0.0;var opacity_card_2=(opacity_card_1>0.0)?0.0:1.0;$('#wipe-animation-card-1').css('opacity',opacity_card_1);$('#wipe-animation-card-2').css('opacity',opacity_card_2);$('#wipe-animation-phone-1').css('opacity',opacity_phone_1);$('#wipe-animation-phone-2').css('opacity',opacity_phone_2);}
function processPinAnimation(){var secure_pos=t("#pin-animation");var top_found=false;for(i=5;i>=1;i--){var trigger_t=0.10+0.6*parseFloat(i)/5.0;var opacity=((trigger_t<=secure_pos&&!top_found)||(i==1&&!top_found))?1.0:0.0;if(opacity>0.0)top_found=true;$("#pin-animation-"+i).css('opacity',opacity);}}
function positionnutrifio(){sizing.win.height=parseFloat($(window).height());sizing.win.offset=parseFloat($(window).scrollTop());var pin_width=0.75*Math.min(571.0,parseFloat($('#pin-animation').outerWidth()));var pin_multiplier=pin_width/571.0;var pin_height=pin_multiplier*770.0;var pin_left=(parseFloat($('#pin-animation').outerWidth())-pin_width)/2.0;$('#pin-animation').css('height',(pin_height+10)+'px');for(i=1;i<6;i++){var opacity=1.0;$("#pin-animation-"+i).css('width',pin_width+'px');$("#pin-animation-"+i).css('height',pin_height+'px');$("#pin-animation-"+i).css('left',pin_left+'px');}
var wipe_width=Math.min(489.0,parseFloat($('#wipe-animation').outerWidth()));var wipe_multiplier=wipe_width/489.0;var wipe_height=wipe_multiplier*506.0;var card_width=wipe_multiplier*238.0;var card_height=wipe_multiplier*56.0;var card_left=wipe_multiplier*217.0;var card_top=wipe_multiplier*404.0;$('#wipe-animation').css('height',(wipe_height+10)+'px');$('#wipe-animation-phone-1').css('width',wipe_width+'px');$('#wipe-animation-phone-1').css('height',wipe_height+'px');$('#wipe-animation-phone-2').css('width',wipe_width+'px');$('#wipe-animation-phone-2').css('height',wipe_height+'px');$('#wipe-animation-card-1').css('width',card_width+'px');$('#wipe-animation-card-1').css('height',card_height+'px');$('#wipe-animation-card-2').css('width',card_width+'px');$('#wipe-animation-card-2').css('height',card_height+'px');$('#wipe-animation-card-1').css('left',card_left+'px');$('#wipe-animation-card-1').css('top',card_top+'px');$('#wipe-animation-card-2').css('left',card_left+'px');$('#wipe-animation-card-2').css('top',card_top+'px');var facial_width=Math.min(400.0,parseFloat($('#facial-animation').outerWidth()));var facial_multiplier=facial_width/400.0;var facial_height=facial_multiplier*460.0;var facial_left=(parseFloat($('#facial-animation').outerWidth())-facial_width)/2.0;var video_width=facial_multiplier*328.0;var video_height=facial_multiplier*270.0;var video_top=facial_multiplier*190.0;var video_left=facial_multiplier*40.0;$('#facial-animation').css('height',(facial_height+10)+'px');$('#facial-animation-phone').css('width',facial_width+'px');$('#facial-animation-phone').css('height',facial_height+'px');$('#facial-animation-phone').css('left',facial_left+'px');$('#facial-animation-video').css('width',video_width+'px');$('#facial-animation-video').css('height',video_height+'px');$('#facial-animation-video').css('top',video_top+'px');$('#facial-animation-video').css('left',facial_left+video_left+'px');var proximity_base_width=400.0;var proximity_multiplier=Math.min(1.0,parseFloat($('#proximity-animation-width-reference').outerWidth())/proximity_base_width);var proximity_width=Math.min(proximity_base_width,$('#proximity-animation-width-reference').outerWidth());var proximity_height=Math.min(460.0,proximity_width*460.0/400.0);$('#proximity-animation-width-reference').css('height',(proximity_height+10)+'px');$('#proximity-animation').css('width',proximity_width+'px');$('#proximity-animation').css('height',proximity_height+'px');$('#proximity-animation').css('bottom',($('#app-proximity-alerts').outerHeight()-proximity_height)/2.0+'px');var iphone_width=proximity_height*400.0/460.0;$('#proximity-iphone').css('width',iphone_width+'px');$('#proximity-iphone').css('height',proximity_height+'px');$('#proximity-iphone').css('left',($('#proximity-animation').outerWidth()-iphone_width)/2.0+'px');}});