function isMobile(){var thres_w=740;if($(window).width()<thres_w)return true;return false;}
$(document).ready(function(){function limit(v,range){if(typeof range==='undefined')range=[0.0,1.0];return Math.min(range[1],Math.max(range[0],v));}
function genObject(str,desc,img_dim,text_dim,bounds){return{name:str,img:{id:"#everything-animation-"+str+"-img",width:parseFloat(img_dim[0]),height:parseFloat(img_dim[1]),rawWidth:parseFloat(img_dim[0]),rawHeight:parseFloat(img_dim[1]),url:"assets/card-animations/everything/"+str+".png"},text:{id:"#everything-animation-"+str+"-text",width:parseFloat(text_dim[0]),height:parseFloat(text_dim[1]),rawWidth:parseFloat(text_dim[0]),rawHeight:parseFloat(text_dim[1]),description:desc,url:"assets/card-animations/everything/"+str+"-screen.png"},bounds:{begin:bounds[0],middle:(bounds[0]+bounds[1])/2.0,end:bounds[1]}}}
var $con=$('#everything-animation');var sizing={win:{height:parseFloat($(window).height()),offset:parseFloat($(window).scrollTop())},con:{width:parseFloat($con.outerWidth()),height:parseFloat($con.outerHeight()),multiplier:1.0}};var PLASTC=genObject('iphone6_gold_empty','iphone6_gold_empty',[550,965],[370,86],[0.0,1.0]);PLASTC.text.offsetRatio=0.33;var UPC=[genObject('water','Even Water',[1024,647],[370,86],[0.1,0.35]),genObject('chips','Friday night chips',[1024,647],[370,86],[0.25,0.5]),genObject('lemonade','Your favourite lemonade',[1024,647],[370,86],[0.25,0.5]),genObject('candy','A piece of Candy',[1024,647],[370,86],[0.1,0.35]),genObject('cola','Your Cola of choice',[1024,647],[370,86],[0.55,0.8]),genObject('beer','Your favourite beer',[1024,647],[370,86],[0.7,0.95]),genObject('mints','Your beloved Mints',[1024,647],[370,86],[0.7,0.95])];function hydrateEverythingMobile(){$con.append('<img src="assets/card-animations/everything/card_carousel_mobile.png">');}

function hydrateEverything(){$con.css('height',PLASTC.img.height+'px');$con.append('<div id="'+PLASTC.img.id.substring(1)+'" style="position:absolute; top:0px;left:'+(-1.0*PLASTC.img.width-1.0)+'px; z-index:6;"><img src="'+PLASTC.img.url+'"></div>');$(UPC).each(function(index,v){$con.append('<div id="'+v.img.id.substring(1)+'" style="position:absolute; top:0px; left:'+(-1.0*v.img.width-1.0)+'px; z-index:4;width:'+v.img.width+'px;height:'+v.img.height+'px;"><img src="'+v.img.url+'"></div>');$con.append('<div id="'+v.text.id.substring(1)+'" style="position:absolute; top:0px; left:'+(-1.0*v.text.width-1.0)+'px; width:'+v.text.width+'px; height:'+v.text.height+'px; z-index:7;opacity:0.0;"><img src="'+v.text.url+'"></div>');});}

function hydrateSecureMobile(){$("#secure-animation").append('<img src="assets/card-animations/security/mobile_flat_enter_your_pin.png">');}
function hydrateSecure(){$("#secure-animation").append('<img src="assets/card-animations/security/website_flat_card.png">');for(i=0;i<7;i++){var opacity=1.0;$("#secure-animation").append('<div id="secure-animation-'+i+'" style="z-index:'+(i+4)+';opacity:'+opacity+';position:absolute;top:0px;">'+'<img src="assets/card-animations/security/enter_your_pin_'+i+'.png"></div>');}}

function hydrateSpecsMobile(){}
function hydrateSpecs(){$("#specs-animation").append('<div id="specs-animation-text" style="position:absolute;top:0px;left:0px;z-index:100;">'+'<table><tbody><tr><td>Material</td><td>-------</td></tr>'+'<tr><td>Color</td><td>-------</td></tr>'+'<tr><td>Width</td><td>-------</td></tr>'+'<tr><td>Length</td><td>-------</td></tr>'+'<tr><td>Thickness</td><td>-------</td></tr>'+'<tr><td>Weight</td><td>-------</td></tr>'+'<tr><td>Connectivity</td><td>-------</td></tr></tbody></table></div>');for(i=0;i<24;i++){var opacity=(i==0)?1.0:0.0;$("#specs-animation").append('<div id="specs-animation-'+i+'" style="z-index:'+(i+4)+';opacity:'+opacity+';position:absolute;top:0px;">'+'<img src="assets/card-animations/specs/tech_specs_anim/Plastc_card_tech_specs_'+i+'.jpg"></div>');}}

function processSpecsAnimation(){var secure_pos=remap_to_bounds(t("#specs-animation"),[0.0,0.2]);var active_i=parseInt(Math.floor(secure_pos*22.999));for(i=23;i>=0;i--){var opacity=(active_i==i)?1.0:0.0;$("#specs-animation-"+i).css('opacity',opacity);}}
function t(e){if(typeof e==='undefined')e=PLASTC.img.id;return 1.0- limit(parseFloat($(e).offset().top+$(e).outerHeight()/2-sizing.win.offset)/sizing.win.height);}
function remap_to_bounds(v,bounds){if(typeof bounds.begin!=='undefined'&&typeof bounds.end!=='undefined')return limit(parseFloat(v-bounds.begin)/parseFloat(bounds.end-bounds.begin));else return limit(parseFloat(v-bounds[0])/parseFloat(bounds[1]-bounds[0]));}
function d(m){$('#everything-debug').html(m);}

function animateCardToLeft(e,forced){if(typeof forced==='undefined')forced=true;var shrink_factor=0.5;$(e.img.id).addClass('animate-to-left');var css={left:0.1*sizing.con.width+'px',top:((sizing.con.height- shrink_factor*e.img.height)/2.0)+'px',width:(shrink_factor*e.img.width)+'px',height:(shrink_factor*e.img.height)+'px'}
if(forced){$(e.img.id).css(css);$(e.img.id).css('z-index',4);$(e.text.id).css('opacity',0.0);$(e.img.id).removeClass('animate-to-left');}
else $(e.img.id).animate(css,{duration:1000,specialEasing:{left:'easeOutCirc',top:'easeInCirc',width:'easeInCirc',height:'easeInCirc'},complete:function(){$(e.img.id).css('z-index',4);$(e.text.id).css('opacity',0.0);$(e.img.id).removeClass('animate-to-left');}});}
function animateCardToRight(e,forced){if(typeof forced==='undefined')forced=true;var shrink_factor=0.5;$(e.img.id).addClass('animate-to-right');var right_based={}
$(e.img.id).css(right_based);var css={left:0.9*sizing.con.width- shrink_factor*e.img.width+'px',top:((sizing.con.height- shrink_factor*e.img.height)/2.0)+'px',width:(shrink_factor*e.img.width)+'px',height:(shrink_factor*e.img.height)+'px'}
if(forced){$(e.img.id).css(css);$(e.img.id).css('z-index',5);$(e.img.id).removeClass('animate-to-right');}
else $(e.img.id).animate(css,{duration:1000,specialEasing:{right:'easeOutCirc',top:'easeInCirc',width:'easeInCirc',height:'easeInCirc'},complete:function(){$(e.img.id).css('z-index',5);$(e.img.id).removeClass('animate-to-right');}});}

function animateCardToFront(e,forced){if(typeof forced==='undefined')forced=true;var shrink_factor=0.9;$(e.img.id).addClass('animate-to-front');var left_based={}
var css={left:((sizing.con.width- e.img.width)/2.0)+'px',top:((sizing.con.height- shrink_factor*e.img.height)/2.0)+'px',width:(shrink_factor*e.img.width)+'px',height:(shrink_factor*e.img.height)+'px'}
if(forced){$(e.text.id).css('opacity',1.0);$(e.img.id).css(css);$(e.img.id).css(left_based);$('#everything-animation-caption').html(e.text.description);$(e.img.id).removeClass('animate-to-front');}
else $(e.img.id).animate(css,{duration:1000,specialEasing:{right:'easeInCirc',top:'easeOutCirc',width:'easeOutCirc',height:'easeOutCirc'},complete:function(){$(e.text.id).css('opacity',1.0);$('#everything-animation-caption').html(e.text.description);$(e.img.id).css(left_based);$(e.img.id).removeClass('animate-to-front');}});}
function animateCardToBack(e,forced){if(typeof forced==='undefined')forced=true;var shrink_factor=0.2;$(e.img.id).addClass('animate-to-back');var css={left:((sizing.con.width- shrink_factor*e.img.width)/2.0)+'px',top:((sizing.con.height- shrink_factor*e.img.height)/2.0)+'px',width:(shrink_factor*e.img.width)+'px',height:(shrink_factor*e.img.height)+'px'}
if(forced){$(e.img.id).css(css);$(e.img.id).removeClass('animate-to-back');}
else $(e.img.id).animate(css,{duration:1000,specialEasing:{left:'easeInCirc',top:'easeOutCirc',width:'easeOutCirc',height:'easeOutCirc'},complete:function(){$(e.img.id).removeClass('animate-to-back');}});}
var step_count=0;function renderStep(forced){window.clearTimeout(window.step_timeout);if(typeof forced==='undefined')forced=true;var to_back=UPC[((step_count+1)%UPC.length)];var to_left=UPC[((step_count+2)%UPC.length)];var to_front=UPC[((step_count+3)%UPC.length)];var to_right=UPC[((step_count+4)%UPC.length)];animateCardToLeft(to_left,forced);animateCardToFront(to_front,forced);animateCardToRight(to_right,forced);animateCardToBack(to_back,forced);animateCardToBack(UPC[((step_count+5)%UPC.length)],true);animateCardToBack(UPC[((step_count+6)%UPC.length)],true);animateCardToBack(UPC[((step_count)%UPC.length)],true);step_count++;window.step_timeout=setTimeout(function(){renderStep(false);},2000);}
if($('body.app').length==0){}
else if(isMobile()){hydrateEverythingMobile();hydrateProximityAnimationMobile();hydrateSecureMobile();hydrateFinancialAnimationMobile();}
else{hydrateEverything();hydrateSecure();hydrateProximityAnimation();hydrateFinancialAnimation();positionPlastc();renderStep(true);processSecureAnimation();processProximityAnimation();processFinancialAnimation();$(window).resize(function(){positionPlastc();processSecureAnimation();processProximityAnimation();$(UPC).each(function(index,v){$(v.img.id).finish();$(v.text.id).css('opacity',0.0);});renderStep(false);});$(window).scroll(function(){sizing.win.offset=parseFloat($(window).scrollTop());processSecureAnimation();processProximityAnimation();processFinancialAnimation();});}
function hydrateProximityAnimationMobile(){$('#proximity-animation-width-reference').html('<img src="assets/card-animations/proximity/phone.png">');}
function hydrateProximityAnimation(){$('#proximity-alerts').prepend(['<div id="proximity-animation" style="position:absolute;right:0px;bottom:0px;overflow:hidden;z-index:4;">','<div id="proximity-iphone" style="bottom:0px;right:0px;position:absolute;z-index:8;">','<img src="assets/card-animations/proximity/phone.png">','</div>','<div id="proximity-card" style="top:0px;right:0px;position:absolute;z-index:7;">','<img src="assets/card-animations/proximity/card.png">','</div>','</div>'].join('\n'));}
function hydrateFinancialAnimationMobile(){$('#financial-animation').append('<img id="financial-animation-2" src="assets/card-animations/financial/fast_lookups_iphone6_silver_results.png">');}

function hydrateFinancialAnimation(){$('#financial-animation').append('<div id="financial-animation-1" style="position:absolute;top:0px;left:0px;opacity:1.0;z-index:5;"><img src="assets/card-animations/financial/fast_lookups_iphone6_silver_barcode.png"></div>');$('#financial-animation').append('<div id="financial-animation-2" style="position:absolute;top:0px;left:0px;opacity:0.0;z-index:6;"><img src="assets/card-animations/financial/fast_lookups_iphone6_silver_results.png"></div>');}
function processFinancialAnimation(){var pos_card=(t("#financial-animation-1")>0.45)?1.0:0.0;$('#financial-animation-2').css('opacity',pos_card);}
function processProximityAnimation(){var pos_iphone=remap_to_bounds(t("#proximity-alerts"),[0.25,0.5]);var pos_card=remap_to_bounds(t("#proximity-alerts"),[0.2,0.4]);var frame_offset=($('#proximity-alerts').outerHeight()- $('#proximity-animation').outerHeight())/2.0;$('#proximity-iphone').css('bottom',(-1.0*(1.0-pos_iphone)*$('#proximity-iphone').outerHeight())+'px');var card_ratio=400.0/458.0;var card_width=(0.15+0.85*(1.0-pos_card))*$('#proximity-animation').outerWidth();var card_height=card_width*card_ratio;$('#proximity-card').css('width',card_width+'px');$('#proximity-card').css('height',card_height+'px');$('#proximity-card').css('right',($('#proximity-animation').outerWidth()-card_width)/2.0+'px');$('#proximity-card').css('top',($('#proximity-animation').outerHeight()-card_height)/2.0+'px');}

function processSecureAnimation(){var secure_pos=t("#secure-animation");var top_found=false;for(i=6;i>=0;i--){var trigger_t=0.15+0.75*parseFloat(i)/7.0;var opacity=((trigger_t<=secure_pos&&!top_found)||(i==0&&!top_found))?1.0:0.0;if(opacity>0.0)top_found=true;$("#secure-animation-"+i).css('opacity',opacity);}}
function positionPlastc(){sizing.con.width=parseFloat($con.outerWidth());sizing.win.height=parseFloat($(window).height());sizing.win.offset=parseFloat($(window).scrollTop());PLASTC.img.width=Math.min(PLASTC.img.rawWidth,0.42*sizing.con.width);sizing.con.multiplier=PLASTC.img.width/PLASTC.img.rawWidth;PLASTC.img.height=sizing.con.multiplier*PLASTC.img.rawHeight;sizing.con.height=PLASTC.img.height;$con.css('height',sizing.con.height+'px');$(PLASTC.img.id).css('width',PLASTC.img.width+'px');$(PLASTC.img.id).css('height',PLASTC.img.height+'px');$(PLASTC.img.id).css('left',Math.max(0,(sizing.con.width-PLASTC.img.width)/2)+'px');$(UPC).each(function(index,v){v.img.width=sizing.con.multiplier*PLASTC.img.width;v.img.height=sizing.con.multiplier*PLASTC.img.width*v.img.rawHeight/v.img.rawWidth;v.text.width=sizing.con.multiplier*v.text.rawWidth;v.text.height=sizing.con.multiplier*v.text.rawHeight;$(v.text.id).css('width',v.text.width+'px');$(v.text.id).css('height',v.text.height+'px');$(v.text.id).css('left',Math.max(0,(sizing.con.width-v.text.width)/2)+'px');$(v.text.id).css('top',Math.max(0,(PLASTC.img.height*PLASTC.text.offsetRatio)-v.text.height/2.0)+'px');});var secure_multiplier=parseFloat($('#secure-animation').outerWidth())/458.0;$('#secure-animation div').css('top',(secure_multiplier*157.0)+'px');$('#secure-animation div').css('left',(secure_multiplier*44.0)+'px');$('#secure-animation div').css('width',(secure_multiplier*370.0)+'px');$('#secure-animation div').css('height',(secure_multiplier*86.0)+'px');var proximity_base_width=400.0;var proximity_multiplier=Math.min(1.0,parseFloat($('#proximity-animation-width-reference').outerWidth())/proximity_base_width);var proximity_width=Math.min(proximity_base_width,$('#proximity-animation-width-reference').outerWidth());var proximity_height=Math.min(Math.min(460.0,proximity_width*460.0/400.0),$('#proximity-alerts').outerHeight());$('#proximity-animation').css('width',proximity_width+'px');$('#proximity-animation').css('height',proximity_height+'px');$('#proximity-animation').css('bottom',($('#proximity-alerts').outerHeight()-proximity_height)/2.0+'px');var iphone_width=proximity_height*400.0/460.0;$('#proximity-iphone').css('width',iphone_width+'px');$('#proximity-iphone').css('height',proximity_height+'px');$('#proximity-iphone').css('right',($('#proximity-animation').outerWidth()-iphone_width)/2.0+'px');var financial_width=parseFloat($('#financial-animation').outerWidth());var financial_height=financial_width*506.0/489.0;$('#financial-animation').css('height',(financial_height+10)+'px');$('#financial-animation-1').css('width',financial_width+'px');$('#financial-animation-1').css('height',(financial_height)+'px');$('#financial-animation-2').css('width',financial_width+'px');$('#financial-animation-2').css('height',(financial_height)+'px');}});